name: ai-ml-template
channels:
  - conda-forge
  - nodefaults # Attempt to block default channels for conda env
dependencies:
  - python=3.11.5
  - poetry=1.4.0
  - conda-lock=1.4.0
platforms:
  - linux-64
  - osx-64 # Intel-based Apple Systems
  - osx-arm64  # Apple Silicon-based Apple Systems
  - linux-aarch64  # Linux ARM system, can use on Docker on Apple Silicon Apple Systems
  - win-64